version: "3.7"
services:
  web:
    build:
      context: ./apache-php
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "4000:80"
    volumes:
      - ./www:/var/www
      - ./httpd_log:/var/log/httpd
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
